
@domain = dale.instructure.com
@apiURL = {{domain}}/api/v1
@userToken = {{$dotenv CANVAS_TOKEN}}

##########################################
# TEST URL
##########################################

GET https://{{apiURL}}/courses/571
Authorization: Bearer {{userToken}}

##########################################
# USER: Basic User Details
##########################################
GET https://{{apiURL}}/users/self
Authorization: Bearer {{userToken}}

##########################################
# USER: Extended User Details
##########################################
GET https://{{apiURL}}/users/self/profile
Authorization: Bearer {{userToken}}

##########################################
# USER: Activity Stream Summary
##########################################
GET https://{{apiURL}}/users/self/activity_stream/summary
Authorization: Bearer {{userToken}}


